In [128]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [108]:
#definition of the sigmoid function

def sigmoid(z):
    k=z
    f=1/(1+(np.e)**-k)
    return f

In [155]:
def y_out(x,w,b):
    x_d,w_d,b_d=x,w,b
    m,n=x_d.shape
    a=sigmoid(np.dot(w_d,x.T)+b_d)
    
    return a

In [145]:
#cost 
def cost(x,y,w,b):
    
    x_d,y_d,w_d,b_d=x,y,w,b
    m,n=x.shape
    cost=0.
    
    for i in range(m):
        cost_i=(-y[i]*(np.log(sigmoid(np.dot(w_d,x_d[i]))+b_d)))-((1-y_d[i])*(np.log(1-sigmoid(np.dot(w_d,x_d[i]))+b_d)))
        cost+=cost_i
        
    return cost/m
        
        

In [146]:
def gradient(x,y,w,b):
    
    x_d,y_d,w_d,b_d=x,y,w,b
    m,n=x_d.shape
    dj_dw=np.zeros(n)#derivative terms for each feature
    dj_db=0.
    
    for i in range(m):
        z_wb=np.dot(w,x_d[i])+b_d
        f_wb=sigmoid(z_wb)
        
        for j in range(n):
            dj_dw[j]+=(f_wb-y_d[i])*x_d[i][j]
        dj_db+=f_wb-y_d[i]
        
    dj_dw=dj_dw/m
    dj_db=dj_db/m
    
    return dj_dw,dj_db



In [147]:
#def gradient_descent(x,y,w_in,b_in,alpha,num_iters):
    
    x_d,y_d,w_d,b_d=x,y,w_in,b_in
    m,n=x_d.shape
   
    for i in range(num_iters):
        
        dj_dw,dj_db=gradient(x_d,y_d,w_d,b_d)
        
        w_d=w_d-alpha*dj_dw
        b_d=b_d-alpha*dj_db
       
    
    return w_d,b_d    
        

In [148]:
def predict(x,w,b):
    
    x_d,w_d,b_d=x,w,b
    m,n=x_d.shape
    p=np.zeros(m)
    
    for i in range(m):
        z_wb=np.dot(w_d,x_d[i])+b_d
        f_wb=sigmoid(z_wb)
        
        if(f_wb>=0.5):
            p[i]=1
        else:
            p[i]=0
            
    return p
        

In [150]:
dataset=pd.read_csv("ex2data1.csv")
x_train=dataset.iloc[:,:-1].values
y_train=dataset.iloc[:,-1].values
y_train=y_train.reshape(len(y_train),1)

In [188]:
w=np.array([[1,2]])
b=-1

In [189]:
alpha=1e-6

In [193]:
for i in range(10000):
    dw,db=gradient(x_train,y_train,w,b)
    w=w-alpha*(dw)
    b=b-alpha*(db)

In [194]:
w

array([[0.7725924 , 1.76591211]])

In [195]:
b

array([-1.00433333])

In [196]:
w

array([[0.7725924 , 1.76591211]])

In [197]:
b

array([-1.00433333])